// ==========================================================================
// CAVA Menu 2026 – Complete Dataset, Builder, Nutrition & Editorial Content
// Verified against CAVA Group SEC Filings & Official Published Nutrition
// ==========================================================================

export const MENU_DATA = {
  meta: {
    title: "CAVA Menu 2026 – Prices, Calories & Full Mediterranean Food Guide",
    reviewDate: "April 2026",
    totalLocations: "459+",
    totalStates: "29 States + Washington, D.C.",
    ticker: "NYSE: CAVA",
    verifiedBy: "Menu Content Specialist & Editorial Review Team"
  },

  categories: [
    { id: "all", label: "All Items", icon: "✨" },
    { id: "in-season", label: "In Season", icon: "🌱" },
    { id: "build-your-own", label: "Build Your Own", icon: "🥗" },
    { id: "bowls", label: "Bowls", icon: "🥣" },
    { id: "pitas", label: "Pita", icon: "🥙" },
    { id: "sides", label: "Sides", icon: "🧆" },
    { id: "kids-meal", label: "Kids Meal", icon: "🧒" },
    { id: "drinks", label: "Drinks", icon: "🍋" },
    { id: "desserts", label: "Desserts", icon: "🍪" }
  ],

  items: [
    // --- CURATED BOWLS ---
    {
      id: "harissa-avocado-bowl",
      name: "Harissa Avocado Bowl",
      category: "bowls",
      price: 15.45,
      priceRange: "$15.00 – $19.89",
      calories: 845,
      calorieRange: "810 – 885 cal",
      protein: "38g",
      carbs: "68g",
      fat: "42g",
      badge: "Most Popular #1",
      isTrending: true,
      dietary: ["high-protein"],
      allergens: ["Sesame", "Dairy"],
      description: "Harissa honey chicken, Crazy Feta®, traditional hummus, ripe avocado slices, pickled onions, crumbled feta, SuperGreens, brown rice, finished with fiery hot harissa vinaigrette.",
      ingredients: ["Harissa Honey Chicken", "Crazy Feta®", "Traditional Hummus", "Fresh Avocado", "Crumbled Feta", "Pickled Onions", "SuperGreens", "Brown Rice", "Hot Harissa Vinaigrette"],
      icon: "🥑"
    },
    {
      id: "chicken-rice-bowl",
      name: "Chicken + Rice Bowl",
      category: "bowls",
      price: 13.45,
      priceRange: "$12.85 – $13.96",
      calories: 712,
      calorieRange: "710 – 715 cal",
      protein: "42g",
      carbs: "64g",
      fat: "28g",
      badge: "Best for First-Timers",
      isTrending: true,
      dietary: ["high-protein"],
      allergens: ["Dairy", "Wheat (if pita crisps)"],
      description: "Grilled herb chicken over saffron basmati rice, traditional hummus, cooling cucumber dill tzatziki, diced Persian cucumbers, tomatoes, pickled red onions, and lemon herb dressing.",
      ingredients: ["Grilled Chicken", "Saffron Basmati Rice", "Traditional Hummus", "Cucumber Tzatziki", "Tomato + Cucumber Salad", "Pickled Onions", "Lemon Herb Dressing"],
      icon: "🍗"
    },
    {
      id: "falafel-crunch-bowl",
      name: "Falafel Crunch Bowl",
      category: "bowls",
      price: 13.75,
      priceRange: "$13.00 – $14.45",
      calories: 860,
      calorieRange: "860 cal",
      protein: "24g",
      carbs: "92g",
      fat: "38g",
      badge: "100% Plant Power",
      isTrending: false,
      dietary: ["vegetarian", "vegan-option"],
      allergens: ["Wheat", "Sesame"],
      description: "Golden crisp falafel balls over black lentils and SuperGreens, accompanied by hummus, roasted eggplant spread, pita crisps, fire-roasted corn, and creamy lemon herb tahini.",
      ingredients: ["Golden Falafel", "Black Lentils", "SuperGreens", "Hummus", "Roasted Eggplant Spread", "Pita Crisps", "Fire-Roasted Corn", "Lemon Herb Tahini"],
      icon: "🧆"
    },
    {
      id: "greek-salad-bowl",
      name: "Greek Salad Bowl",
      category: "bowls",
      price: 12.45,
      priceRange: "$11.55 – $12.85",
      calories: 590,
      calorieRange: "585 – 600 cal",
      protein: "34g",
      carbs: "26g",
      fat: "32g",
      badge: "Fresh & Crisp",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: ["Dairy"],
      description: "Grilled chicken, crisp romaine, diced Persian cucumber & tomato salad, kalamata olives, pickled onions, rich crumbled Greek feta, and classic Greek herb vinaigrette.",
      ingredients: ["Grilled Chicken", "Romaine Lettuce", "Tomato + Cucumber Salad", "Crumbled Feta", "Kalamata Olives", "Pickled Onions", "Greek Vinaigrette"],
      icon: "🥗"
    },
    {
      id: "steak-harissa-bowl",
      name: "Steak + Harissa Bowl",
      category: "bowls",
      price: 15.85,
      priceRange: "$15.05 – $16.55",
      calories: 615,
      calorieRange: "615 cal",
      protein: "41g",
      carbs: "38g",
      fat: "32g",
      badge: "Bold & Savory",
      isTrending: true,
      dietary: ["high-protein", "gluten-free"],
      allergens: ["Dairy", "Sesame"],
      description: "Grilled marinated steak over SuperGreens and saffron basmati rice, Crazy Feta®, fiery harissa, roasted red pepper hummus, pickled onions, and hot harissa vinaigrette.",
      ingredients: ["Grilled Steak", "SuperGreens", "Saffron Basmati Rice", "Crazy Feta®", "Harissa", "Red Pepper Hummus", "Pickled Onions", "Hot Harissa Vinaigrette"],
      icon: "🥩"
    },
    {
      id: "balsamic-date-chicken",
      name: "Balsamic Date Chicken Bowl",
      category: "in-season",
      price: 14.25,
      priceRange: "$14.25",
      calories: 780,
      calorieRange: "780 cal",
      protein: "37g",
      carbs: "52g",
      fat: "36g",
      badge: "In Season",
      isTrending: true,
      dietary: ["high-protein", "gluten-free"],
      allergens: ["Sesame"],
      description: "Grilled chicken, balsamic date vinaigrette, brown rice, supergreens.",
      ingredients: ["Grilled Chicken", "SuperGreens", "Brown Rice", "Balsamic Date Vinaigrette", "Traditional Hummus", "Sesame Tahini"],
      icon: "🥗"
    },
    {
      id: "lemon-herb-chicken",
      name: "Lemon Herb Chicken",
      category: "in-season",
      price: 13.95,
      priceRange: "$13.95",
      calories: 650,
      calorieRange: "650 cal",
      protein: "38g",
      carbs: "48g",
      fat: "38g",
      badge: "In Season",
      isTrending: true,
      dietary: ["high-protein", "gluten-free"],
      allergens: ["Dairy"],
      description: "Lemon herb chicken with saffron basmati rice and arugula.",
      ingredients: ["Lemon Herb Chicken", "Saffron Basmati Rice", "Baby Arugula", "Tzatziki", "Kalamata Olives", "Crumbled Feta"],
      icon: "🍗"
    },
    {
      id: "supergreens-grilled-chicken-bowl",
      name: "SuperGreens + Grilled Chicken Bowl",
      category: "build-your-own",
      price: 12.85,
      priceRange: "$12.50 – $13.50",
      calories: 480,
      calorieRange: "480 cal",
      protein: "33g",
      carbs: "18g",
      fat: "22g",
      badge: "Lowest Calorie / High Protein",
      isTrending: false,
      dietary: ["high-protein", "keto-friendly", "gluten-free"],
      allergens: ["Sesame"],
      description: "High-protein lean powerhouse: grilled chicken breast over raw SuperGreens, roasted vegetables, traditional hummus, pickled onions, and light Greek herb vinaigrette.",
      ingredients: ["Grilled Chicken", "SuperGreens", "Roasted Medley Veggies", "Traditional Hummus", "Pickled Onions", "Greek Vinaigrette"],
      icon: "🌿"
    },
    {
      id: "tahini-caesar-bowl",
      name: "Tahini Caesar Chicken Bowl",
      category: "bowls",
      price: 13.45,
      priceRange: "$12.85 – $14.25",
      calories: 605,
      calorieRange: "550 – 660 cal",
      protein: "42g",
      carbs: "28g",
      fat: "34g",
      badge: "Top Rated Classic",
      isTrending: false,
      dietary: ["high-protein"],
      allergens: ["Dairy", "Sesame", "Wheat (Pita Crisps)"],
      description: "Herb-marinated grilled chicken breast, crisp romaine, parmesan crisps, house pita crisps, Persian cucumbers, pickled red onions, tossed in rich sesame Tahini Caesar.",
      ingredients: ["Herb Grilled Chicken", "Romaine", "Parmesan Crisps", "Pita Crisps", "Persian Cucumbers", "Pickled Onions", "Tahini Caesar Dressing"],
      icon: "🥗"
    },
    {
      id: "keto-greens-steak-bowl",
      name: "Keto Greens + Steak Bowl",
      category: "build-your-own",
      price: 15.50,
      priceRange: "$15.00 – $16.50",
      calories: 615,
      calorieRange: "615 cal",
      protein: "40g",
      carbs: "14g",
      fat: "42g",
      badge: "Strict Keto Pick",
      isTrending: false,
      dietary: ["high-protein", "keto-friendly", "gluten-free"],
      allergens: ["Dairy"],
      description: "Designed for low-carb success: grilled tender steak over crisp romaine and arugula, Crazy Feta®, cucumber tzatziki, fresh avocado, and olive oil Greek dressing.",
      ingredients: ["Grilled Steak", "Romaine & Arugula", "Crazy Feta®", "Cucumber Tzatziki", "Fresh Avocado", "Greek Dressing"],
      icon: "🥩"
    },
    {
      id: "spicy-lamb-avocado-bowl",
      name: "Spicy Lamb + Avocado Bowl",
      category: "bowls",
      price: 15.95,
      priceRange: "$15.25 – $17.50",
      calories: 785,
      calorieRange: "780 – 795 cal",
      protein: "44g",
      carbs: "54g",
      fat: "44g",
      badge: "Rich & Savory",
      isTrending: false,
      dietary: ["high-protein"],
      allergens: ["Dairy", "Sesame"],
      description: "Spicy braised lamb meatballs, creamy Crazy Feta®, hummus, sliced avocado, fire-roasted corn, and brown rice with hot harissa vinaigrette.",
      ingredients: ["Spicy Lamb Meatballs", "Crazy Feta®", "Hummus", "Fresh Avocado", "Fire-Roasted Corn", "Brown Rice", "Hot Harissa"],
      icon: "🍖"
    },

    // --- WARM PITAS ---
    {
      id: "greek-chicken-pita",
      name: "Greek Chicken Pita",
      category: "pitas",
      price: 12.50,
      priceRange: "$12.00 – $13.50",
      calories: 720,
      calorieRange: "720 cal",
      protein: "38g",
      carbs: "62g",
      fat: "32g",
      badge: "Portable Favorite",
      isTrending: true,
      dietary: ["high-protein"],
      allergens: ["Wheat", "Dairy"],
      description: "Damascus Bakery sprouted grain warm pita packed with grilled chicken, tzatziki, feta crumbles, tomato cucumber salad, and Greek vinaigrette.",
      ingredients: ["Sprouted Grain Pita", "Grilled Chicken", "Cucumber Tzatziki", "Crumbled Feta", "Tomato Cucumber Salad", "Greek Vinaigrette"],
      icon: "🥙"
    },
    {
      id: "spicy-chicken-avocado-pita",
      name: "Spicy Chicken + Avocado Pita",
      category: "pitas",
      price: 13.95,
      priceRange: "$13.50 – $15.50",
      calories: 995,
      calorieRange: "970 – 1,030 cal",
      protein: "46g",
      carbs: "74g",
      fat: "48g",
      badge: "Loaded & Spicy",
      isTrending: true,
      dietary: ["high-protein"],
      allergens: ["Wheat", "Dairy", "Sesame"],
      description: "Fiery harissa chicken wrapped with fresh avocado, Crazy Feta®, traditional hummus, pickled onions, and hot harissa vinaigrette in warm pita flatbread.",
      ingredients: ["Sprouted Grain Pita", "Harissa Honey Chicken", "Fresh Avocado", "Crazy Feta®", "Hummus", "Pickled Onions", "Hot Harissa"],
      icon: "🥙"
    },
    {
      id: "steak-feta-pita",
      name: "Steak + Feta Pita",
      category: "pitas",
      price: 14.95,
      priceRange: "$14.00 – $16.50",
      calories: 810,
      calorieRange: "810 cal",
      protein: "42g",
      carbs: "58g",
      fat: "38g",
      badge: "Hearty Meat Pita",
      isTrending: false,
      dietary: ["high-protein"],
      allergens: ["Wheat", "Dairy"],
      description: "Marinated grilled steak wrapped with Crazy Feta®, fire-roasted charred broccoli, pickled onions, romaine, and Greek vinaigrette.",
      ingredients: ["Sprouted Grain Pita", "Grilled Steak", "Crazy Feta®", "Charred Broccoli", "Pickled Onions", "Romaine"],
      icon: "🥩"
    },
    {
      id: "crispy-falafel-pita",
      name: "Crispy Falafel Pita Pocket",
      category: "pitas",
      price: 11.25,
      priceRange: "$11.00 – $12.50",
      calories: 620,
      calorieRange: "620 cal",
      protein: "22g",
      carbs: "78g",
      fat: "26g",
      badge: "Vegetarian Pick",
      isTrending: false,
      dietary: ["vegetarian"],
      allergens: ["Wheat", "Sesame", "Dairy (Tzatziki)"],
      description: "Stone-baked warm pita filled with golden falafel balls, cucumber tzatziki, hummus, Persian cucumbers, and lemon tahini.",
      ingredients: ["Sprouted Grain Pita", "Golden Falafel", "Tzatziki", "Hummus", "Persian Cucumbers", "Lemon Tahini"],
      icon: "🧆"
    },

    // --- SIDES & SCRATCH-MADE DIPS ---
    {
      id: "hummus-trio-chips",
      name: "Hummus Trio + Pita Chips",
      category: "sides",
      price: 10.50,
      priceRange: "$10.00 – $11.50",
      calories: 680,
      calorieRange: "680 cal",
      protein: "18g",
      carbs: "84g",
      fat: "32g",
      badge: "Best Value for Sharing",
      isTrending: true,
      dietary: ["vegetarian", "vegan-option"],
      allergens: ["Sesame", "Wheat"],
      description: "Three generous portions of scratch-made dips (Traditional Hummus, Red Pepper Hummus, Crazy Feta® or Eggplant Spread) served with seasoned pita chips.",
      ingredients: ["Traditional Hummus", "Red Pepper Hummus", "Crazy Feta®", "Baked Pita Chips"],
      icon: "🫓"
    },
    {
      id: "crazy-feta-side",
      name: "Crazy Feta® (8oz Tub)",
      category: "sides",
      price: 4.35,
      priceRange: "$3.55 – $4.35",
      calories: 340,
      calorieRange: "340 cal",
      protein: "12g",
      carbs: "6g",
      fat: "28g",
      badge: "Legendary Whipped Dip",
      isTrending: true,
      dietary: ["vegetarian", "gluten-free"],
      allergens: ["Dairy"],
      description: "Whipped Greek feta blended with charred jalapeño peppers, garlic, and extra virgin olive oil.",
      ingredients: ["Greek Feta", "Charred Jalapeños", "Garlic", "Olive Oil"],
      icon: "🧀"
    },
    {
      id: "traditional-hummus-side",
      name: "Traditional Hummus (8oz Tub)",
      category: "sides",
      price: 3.95,
      priceRange: "$3.55 – $4.15",
      calories: 270,
      calorieRange: "270 cal",
      protein: "9g",
      carbs: "27g",
      fat: "15g",
      badge: "Free with Bowls",
      isTrending: false,
      dietary: ["vegan", "gluten-free", "dairy-free"],
      allergens: ["Sesame"],
      description: "Silky scratch-made garbanzo bean dip whipped with tahini, lemon juice, garlic, and cumin.",
      ingredients: ["Chickpeas", "Tahini", "Garlic", "Lemon Juice", "Olive Oil"],
      icon: "🧆"
    },
    {
      id: "classic-pita-chips",
      name: "Classic Seasoned Pita Chips",
      category: "sides",
      price: 2.55,
      priceRange: "$2.55 – $3.25",
      calories: 240,
      calorieRange: "240 cal",
      protein: "6g",
      carbs: "38g",
      fat: "7g",
      badge: "Damascus Bakery",
      isTrending: false,
      dietary: ["vegan"],
      allergens: ["Wheat"],
      description: "Crunchy oven-baked pita chips seasoned with sea salt and Mediterranean spices.",
      ingredients: ["Sprouted Grain Pita", "Sea Salt", "Olive Oil", "Spices"],
      icon: "🥨"
    },
    {
      id: "cinnamon-sugar-pita-chips",
      name: "Cinnamon Sugar Pita Chips",
      category: "sides",
      price: 3.25,
      priceRange: "$3.00 – $3.75",
      calories: 290,
      calorieRange: "290 cal",
      protein: "5g",
      carbs: "44g",
      fat: "8g",
      badge: "Sweet Crunch",
      isTrending: false,
      dietary: ["vegetarian"],
      allergens: ["Wheat"],
      description: "Oven-baked pita chips dusted with Saigon cinnamon and cane sugar for a light dessert crunch.",
      ingredients: ["Baked Pita", "Cinnamon", "Cane Sugar", "Butter Oil"],
      icon: "🥨"
    },
    {
      id: "plain-side-pita",
      name: "Warm Side Pita Round",
      category: "sides",
      price: 2.00,
      priceRange: "$2.00",
      calories: 230,
      calorieRange: "230 cal",
      protein: "8g",
      carbs: "46g",
      fat: "2g",
      badge: "Fresh Baked",
      isTrending: false,
      dietary: ["vegan"],
      allergens: ["Wheat"],
      description: "Soft, warm sprouted grain pita flatbread from Damascus Bakery in Brooklyn.",
      ingredients: ["Sprouted Wheat Flour", "Water", "Yeast", "Sea Salt"],
      icon: "🫓"
    },

    // --- HOUSE DRINKS ---
    {
      id: "pineapple-mint-juice",
      name: "Pineapple Mint Fresh Juice",
      category: "drinks",
      price: 3.95,
      priceRange: "$3.50 – $4.25",
      calories: 110,
      calorieRange: "110 cal",
      protein: "1g",
      carbs: "27g",
      fat: "0g",
      badge: "Cold Pressed In-House",
      isTrending: true,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      description: "Freshly pressed tropical pineapple juice steeped with crushed garden mint leaves and lime.",
      ingredients: ["Fresh Pineapple Juice", "Spearmint", "Lime Juice", "Pure Cane Sugar"],
      icon: "🍍"
    },
    {
      id: "blueberry-lavender-tea",
      name: "Blueberry Lavender Green Tea",
      category: "drinks",
      price: 3.95,
      priceRange: "$3.50 – $4.25",
      calories: 85,
      calorieRange: "85 cal",
      protein: "0g",
      carbs: "20g",
      fat: "0g",
      badge: "House Brewed",
      isTrending: false,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      description: "Organic Mediterranean green tea steeped with wild blueberries and French lavender blossoms.",
      ingredients: ["Organic Green Tea", "Wild Blueberries", "Lavender Blossoms", "Lemon"],
      icon: "🫐"
    },
    {
      id: "jasmine-green-tea",
      name: "Unsweetened Jasmine Green Tea",
      category: "drinks",
      price: 2.75,
      priceRange: "$2.50 – $3.00",
      calories: 0,
      calorieRange: "0 cal",
      protein: "0g",
      carbs: "0g",
      fat: "0g",
      badge: "Zero Calorie / Zero Sugar",
      isTrending: false,
      dietary: ["vegan", "keto-friendly", "gluten-free"],
      allergens: [],
      description: "Fresh brewed floral jasmine green tea with zero added sweeteners or artificial flavors.",
      ingredients: ["Brewed Jasmine Green Tea Leaf", "Filtered Water"],
      icon: "🍵"
    },

    // --- BAKERY DESSERTS ---
    {
      id: "salted-chocolate-oat-cookie",
      name: "Salted Chocolate Oat Cookie",
      category: "desserts",
      price: 3.25,
      priceRange: "$2.95 – $3.75",
      calories: 320,
      calorieRange: "320 cal",
      protein: "4g",
      carbs: "42g",
      fat: "16g",
      badge: "Customer Favorite Cookie",
      isTrending: true,
      dietary: ["vegetarian"],
      allergens: ["Wheat", "Dairy", "Eggs"],
      description: "Chewy whole rolled oat cookie studded with rich dark chocolate chunks and Maldon sea salt flakes.",
      ingredients: ["Rolled Oats", "Dark Chocolate", "Maldon Sea Salt", "Butter", "Brown Sugar"],
      icon: "🍪"
    },
    {
      id: "greyston-blondie",
      name: "Greyston Bakery Vanilla Blondie",
      category: "desserts",
      price: 3.95,
      priceRange: "$3.50 – $4.30",
      calories: 140,
      calorieRange: "140 cal",
      protein: "2g",
      carbs: "18g",
      fat: "7g",
      badge: "Certified B Corp Partner",
      isTrending: false,
      dietary: ["vegetarian"],
      allergens: ["Wheat", "Dairy", "Eggs"],
      description: "Rich buttery vanilla blondie bar made by Greyston Bakery, known for social open hiring practices.",
      ingredients: ["Cane Sugar", "Butter", "Flour", "Pure Vanilla", "Eggs"],
      icon: "🧁"
    },
    {
      id: "greyston-brownie",
      name: "Greyston Bakery Fudge Brownie",
      category: "desserts",
      price: 3.95,
      priceRange: "$3.50 – $4.30",
      calories: 280,
      calorieRange: "280 cal",
      protein: "3g",
      carbs: "34g",
      fat: "14g",
      badge: "Certified B Corp Partner",
      isTrending: false,
      dietary: ["vegetarian"],
      allergens: ["Wheat", "Dairy", "Eggs"],
      description: "Dense, decadent fudge brownie crafted with Dutch-process cocoa and melted bittersweet chocolate.",
      ingredients: ["Cocoa", "Bittersweet Chocolate", "Butter", "Flour", "Sugar"],
      icon: "🍫"
    },

    // --- KIDS & CATERING ---
    {
      id: "kids-meal-cava",
      name: "CAVA Kids Pita / Bowl Meal",
      category: "kids-meal",
      price: 7.45,
      priceRange: "$7.15 – $7.95",
      calories: 520,
      calorieRange: "480 – 1,210 cal",
      protein: "26g",
      carbs: "58g",
      fat: "18g",
      badge: "Kid Approved Meal",
      isTrending: false,
      dietary: ["high-protein"],
      allergens: ["Wheat", "Dairy"],
      description: "Smaller kid-friendly bowl or mini pita with choice of grilled chicken, 1 mild dip (hummus/tzatziki), mini pita chips, and organic juice box.",
      ingredients: ["Mini Pita / Rice", "Grilled Chicken", "Mild Hummus", "Kid Drink"],
      icon: "🧒"
    },
    {
      id: "catering-bowl-bar",
      name: "Group Bowl Bar (Catering Station)",
      category: "kids-meal",
      price: 175.00,
      priceRange: "$15.00 – $20.00 / person (10 min)",
      calories: 750,
      calorieRange: "Customizable per guest",
      protein: "35g+",
      carbs: "60g",
      fat: "30g",
      badge: "Top Catering Pick",
      isTrending: true,
      dietary: ["high-protein", "vegan-option", "gluten-free-option"],
      allergens: ["Dairy", "Sesame", "Wheat on side"],
      description: "Complete build-your-own Mediterranean buffet station for 10+ people with 2 bases, 2 proteins, 3 signature dips, unlimited toppings, 2 dressings, and pita packs.",
      ingredients: ["Bases", "Proteins", "Dips", "Toppings", "Dressings", "Pita Chips"],
      icon: "🍱"
    },
    {
      id: "catering-pita-packs",
      name: "CAVA Pita Packs (10 Pitas)",
      category: "kids-meal",
      price: 121.00,
      priceRange: "$121.00 per 10-pack",
      calories: 780,
      calorieRange: "720 – 850 cal per pita",
      protein: "38g",
      carbs: "68g",
      fat: "34g",
      badge: "Office Meeting Ready",
      isTrending: false,
      dietary: ["high-protein"],
      allergens: ["Wheat", "Dairy", "Sesame"],
      description: "Box of 10 individually wrapped, pre-assembled Mediterranean pitas (Assorted Chicken, Steak, and Falafel) with pita chips and dips.",
      ingredients: ["10 Assembled Pitas", "Pita Chips", "Dips"],
      icon: "📦"
    }
  ],

  // 5-Step Build Your Own Bowl Configurator Options
  builder: {
    basePrice: 12.95,
    steps: [
      {
        stepId: 1,
        title: "Step 1: Choose Your Base",
        subtitle: "Pick up to 2 bases for your foundation (Calorie impact: 20 – 310 cal)",
        maxSelect: 2,
        required: true,
        options: [
          { id: "supergreens", name: "SuperGreens (Kale, Spinach, Romaine)", calories: 25, protein: 2, carbs: 4, fat: 0, tags: ["vegan", "gluten-free", "low-cal"], icon: "🥗" },
          { id: "arugula-romaine", name: "Baby Arugula & Romaine", calories: 20, protein: 2, carbs: 3, fat: 0, tags: ["vegan", "gluten-free", "low-cal"], icon: "🥬" },
          { id: "saffron-rice", name: "Saffron Basmati Rice", calories: 190, protein: 4, carbs: 40, fat: 2, tags: ["vegan", "gluten-free"], icon: "🍚" },
          { id: "brown-rice", name: "Wild Brown Rice", calories: 170, protein: 4, carbs: 36, fat: 1.5, tags: ["vegan", "gluten-free"], icon: "🌾" },
          { id: "black-lentils", name: "Black Lentils (+18g Protein, +15g Fiber)", calories: 180, protein: 18, carbs: 32, fat: 1, tags: ["vegan", "high-protein", "gluten-free"], icon: "🥣" },
          { id: "right-rice", name: "RightRice™ (High Protein Veggie Rice)", calories: 160, protein: 10, carbs: 28, fat: 1, tags: ["vegan", "high-protein", "gluten-free"], icon: "🌱" }
        ]
      },
      {
        stepId: 2,
        title: "Step 2: Pick Your Protein",
        subtitle: "Select 1 of 8 proteins (Or double up for +$3.50)",
        maxSelect: 1,
        required: true,
        options: [
          { id: "grilled-chicken", name: "Grilled Chicken Breast (28-33g protein)", calories: 200, protein: 34, carbs: 0, fat: 6, extraCost: 0, tags: ["high-protein", "gluten-free"], icon: "🍗" },
          { id: "harissa-honey-chicken", name: "Harissa Honey Chicken (#1 Most Ordered)", calories: 240, protein: 32, carbs: 6, fat: 9, extraCost: 0, tags: ["high-protein"], icon: "🍗" },
          { id: "grilled-steak", name: "Grilled Marinated Steak", calories: 260, protein: 31, carbs: 1, fat: 14, extraCost: 1.50, tags: ["high-protein", "gluten-free"], icon: "🥩" },
          { id: "braised-lamb", name: "Slow-Roasted Braised Lamb", calories: 290, protein: 30, carbs: 2, fat: 18, extraCost: 1.50, tags: ["high-protein"], icon: "🥩" },
          { id: "spicy-lamb-meatballs", name: "Spicy Lamb Meatballs", calories: 270, protein: 28, carbs: 4, fat: 16, extraCost: 1.50, tags: ["high-protein"], icon: "🍖" },
          { id: "glazed-salmon", name: "Glazed Wild Salmon (2026 Special)", calories: 280, protein: 32, carbs: 4, fat: 15, extraCost: 3.25, tags: ["high-protein", "gluten-free"], icon: "🐟" },
          { id: "golden-falafel", name: "Golden Crisp Falafel (Plant-Based)", calories: 220, protein: 9, carbs: 24, fat: 11, extraCost: 0, tags: ["vegan", "vegetarian"], allergen: "Sesame", icon: "🧆" },
          { id: "roasted-veggies", name: "Roasted Medley Vegetables", calories: 110, protein: 4, carbs: 18, fat: 3, extraCost: 0, tags: ["vegan", "gluten-free"], icon: "🥕" }
        ]
      },
      {
        stepId: 3,
        title: "Step 3: Add Dips & Spreads (Up to 3 Free)",
        subtitle: "All 6 scratch-made dips are included free with every bowl",
        maxSelect: 3,
        required: true,
        options: [
          { id: "crazy-feta", name: "Crazy Feta® (Whipped Feta & Jalapeño)", calories: 110, protein: 4, carbs: 2, fat: 9, tags: ["vegetarian"], allergen: "Dairy", icon: "🧀" },
          { id: "traditional-hummus", name: "Traditional Silky Hummus", calories: 90, protein: 3, carbs: 9, fat: 5, tags: ["vegan", "gluten-free"], allergen: "Sesame", icon: "🧆" },
          { id: "red-pepper-hummus", name: "Roasted Red Pepper Hummus", calories: 95, protein: 3, carbs: 10, fat: 5, tags: ["vegan", "gluten-free"], allergen: "Sesame", icon: "🌶️" },
          { id: "tzatziki", name: "Cucumber Dill Tzatziki", calories: 40, protein: 2, carbs: 2, fat: 2.5, tags: ["vegetarian", "gluten-free"], allergen: "Dairy", icon: "🥒" },
          { id: "roasted-eggplant", name: "Roasted Eggplant Dip", calories: 45, protein: 1, carbs: 5, fat: 2.5, tags: ["vegan", "gluten-free", "low-cal"], icon: "🍆" },
          { id: "harissa", name: "Fiery Harissa Paste", calories: 50, protein: 1, carbs: 3, fat: 4, tags: ["vegan", "gluten-free"], icon: "🔥" }
        ]
      },
      {
        stepId: 4,
        title: "Step 4: Load Up on Toppings (Unlimited Free)",
        subtitle: "No upcharge! Best way to add crunch, fiber, and flavor",
        maxSelect: 7,
        required: false,
        options: [
          { id: "fire-roasted-corn", name: "Fire-Roasted Corn", calories: 35, protein: 1, carbs: 7, fat: 0.5, tags: ["vegan"], icon: "🌽" },
          { id: "pickled-onions", name: "Pickled Red Onions", calories: 15, protein: 0, carbs: 3, fat: 0, tags: ["vegan"], icon: "🧅" },
          { id: "crumbled-feta", name: "Greek Crumbled Feta", calories: 60, protein: 4, carbs: 1, fat: 5, tags: ["vegetarian"], allergen: "Dairy", icon: "🧀" },
          { id: "kalamata-olives", name: "Kalamata Olives", calories: 50, protein: 0, carbs: 2, fat: 5, tags: ["vegan"], icon: "🫒" },
          { id: "persian-cucumbers", name: "Diced Persian Cucumbers", calories: 10, protein: 0, carbs: 2, fat: 0, tags: ["vegan"], icon: "🥒" },
          { id: "tomato-cucumber", name: "Tomato + Cucumber Salad", calories: 20, protein: 1, carbs: 4, fat: 0, tags: ["vegan"], icon: "🥗" },
          { id: "fiery-broccoli", name: "Fiery Charred Broccoli", calories: 45, protein: 3, carbs: 6, fat: 1.5, tags: ["vegan"], icon: "🥦" },
          { id: "pita-crisps", name: "House-Baked Pita Crisps", calories: 70, protein: 2, carbs: 12, fat: 2, tags: ["vegan"], allergen: "Wheat", icon: "🥨" },
          { id: "fresh-avocado", name: "Fresh Sliced Avocado", calories: 120, protein: 2, carbs: 6, fat: 10, extraCost: 1.95, tags: ["vegan", "gluten-free"], icon: "🥑" }
        ]
      },
      {
        stepId: 5,
        title: "Step 5: Finish With Dressing (1 Included Free)",
        subtitle: "Tie all flavors together (Tip: ask on side to save calories)",
        maxSelect: 2,
        required: true,
        options: [
          { id: "greek-vinaigrette", name: "Classic Greek Herb Vinaigrette", calories: 120, protein: 0, carbs: 2, fat: 12, tags: ["vegan"], icon: "🌿" },
          { id: "lemon-herb-tahini", name: "Lemon Herb Tahini", calories: 100, protein: 2, carbs: 4, fat: 9, tags: ["vegan"], allergen: "Sesame", icon: "🍋" },
          { id: "hot-harissa-vinaigrette", name: "Hot Harissa Vinaigrette", calories: 110, protein: 0, carbs: 4, fat: 10, tags: ["vegan"], icon: "🌶️" },
          { id: "yogurt-dill", name: "Yogurt Dill Dressing", calories: 70, protein: 2, carbs: 3, fat: 5, tags: ["vegetarian"], allergen: "Dairy", icon: "🥣" },
          { id: "skhug", name: "Skhug (Middle Eastern Herb & Chili)", calories: 80, protein: 1, carbs: 2, fat: 8, tags: ["vegan"], icon: "🌿" },
          { id: "balsamic-date", name: "Balsamic Date Vinaigrette", calories: 130, protein: 0, carbs: 8, fat: 11, tags: ["vegan"], icon: "🍇" },
          { id: "garlic-dressing", name: "Creamy Garlic Dressing", calories: 140, protein: 1, carbs: 2, fat: 15, tags: ["vegetarian"], icon: "🧄" },
          { id: "tahini-caesar", name: "Sesame Tahini Caesar", calories: 130, protein: 2, carbs: 3, fat: 13, tags: ["vegetarian"], allergen: "Sesame", icon: "🥣" }
        ]
      }
    ]
  },

  // Calorie-ranked table from lowest to highest
  calorieRankings: [
    { rank: 1, name: "SuperGreens + Grilled Chicken Bowl", calories: "480 cal", protein: "33g", carbs: "18g", fat: "22g", category: "Bowl", note: "Lowest calorie count, highest protein density" },
    { rank: 2, name: "Tahini Caesar Bowl", calories: "550 – 660 cal", protein: "42g", carbs: "28g", fat: "34g", category: "Bowl", note: "Savory & low carb if pita crisps reduced" },
    { rank: 3, name: "Greek Salad Bowl", calories: "585 – 600 cal", protein: "34g", carbs: "26g", fat: "32g", category: "Bowl", note: "Light & refreshing classic" },
    { rank: 4, name: "Garlicky Chicken Shawarma Bowl", calories: "600 – 660 cal", protein: "39g", carbs: "44g", fat: "28g", category: "Bowl", note: "Robust garlic & herb notes" },
    { rank: 5, name: "Keto Greens + Steak Bowl", calories: "615 cal", protein: "40g", carbs: "14g", fat: "42g", category: "Bowl", note: "Clean keto macro ratio" },
    { rank: 6, name: "Steak + Harissa Bowl", calories: "615 cal", protein: "41g", carbs: "38g", fat: "32g", category: "Bowl", note: "High protein, spicy kick" },
    { rank: 7, name: "Crispy Falafel Pita Pocket", calories: "620 cal", protein: "22g", carbs: "78g", fat: "26g", category: "Pita", note: "100% vegetarian staple" },
    { rank: 8, name: "Lemon Herb Chicken Bowl", calories: "650 cal", protein: "38g", carbs: "50g", fat: "26g", category: "Bowl", note: "Zesty & balanced" },
    { rank: 9, name: "Salmon + Strawberry Sesame Bowl", calories: "700 cal", protein: "37g", carbs: "52g", fat: "36g", category: "Bowl", note: "2026 limited-time seafood item" },
    { rank: 10, name: "Salmon + Yogurt Dill Bowl", calories: "710 cal", protein: "38g", carbs: "48g", fat: "38g", category: "Bowl", note: "2026 chef curation with wild salmon" },
    { rank: 11, name: "Chicken + Rice Bowl", calories: "710 – 715 cal", protein: "42g", carbs: "64g", fat: "28g", category: "Bowl", note: "Safest pick for first-time visitors" },
    { rank: 12, name: "Greek Chicken Pita", calories: "720 cal", protein: "38g", carbs: "62g", fat: "32g", category: "Pita", note: "Portable Mediterranean wrap" },
    { rank: 13, name: "Spicy Lamb + Avocado Bowl", calories: "780 – 795 cal", protein: "44g", carbs: "54g", fat: "44g", category: "Bowl", note: "Hearty and rich spiced meatballs" },
    { rank: 14, name: "Harissa Avocado Bowl", calories: "810 – 885 cal", protein: "38g", carbs: "68g", fat: "42g", category: "Bowl", note: "#1 most popular item on menu" },
    { rank: 15, name: "Steak + Feta Pita", calories: "810 cal", protein: "42g", carbs: "58g", fat: "38g", category: "Pita", note: "Hearty wrapped steak" },
    { rank: 16, name: "Falafel Crunch Bowl", calories: "860 cal", protein: "24g", carbs: "92g", fat: "38g", category: "Bowl", note: "High carb & high fiber plant bowl" },
    { rank: 17, name: "Spicy Chicken + Avocado Pita", calories: "970 – 1,030 cal", protein: "46g", carbs: "74g", fat: "48g", category: "Pita", note: "Loaded pita wrap, highest calorie build" }
  ],

  // Full Allergen Matrix Table
  allergensTable: [
    { item: "Harissa Avocado Bowl", allergens: "Sesame, Dairy", dairy: true, sesame: true, wheat: false, soy: false, egg: false, fish: false },
    { item: "Chicken + Rice Bowl", allergens: "Dairy, Wheat (if pita crisps added)", dairy: true, sesame: false, wheat: true, soy: false, egg: false, fish: false },
    { item: "Falafel Crunch Bowl", allergens: "Wheat, Sesame", dairy: false, sesame: true, wheat: true, soy: false, egg: false, fish: false },
    { item: "Greek Salad Bowl", allergens: "Dairy", dairy: true, sesame: false, wheat: false, soy: false, egg: false, fish: false },
    { item: "Steak + Harissa Bowl", allergens: "Dairy, Sesame", dairy: true, sesame: true, wheat: false, soy: false, egg: false, fish: false },
    { item: "Salmon + Strawberry Bowl", allergens: "Fish (Salmon), Sesame", dairy: false, sesame: true, wheat: false, soy: false, egg: false, fish: true },
    { item: "Spicy Chicken + Avocado Pita", allergens: "Dairy, Wheat, Sesame", dairy: true, sesame: true, wheat: true, soy: false, egg: false, fish: false },
    { item: "Tahini Caesar Bowl", allergens: "Dairy, Sesame, Wheat", dairy: true, sesame: true, wheat: true, soy: false, egg: false, fish: false },
    { item: "Pita Bread / Pita Chips", allergens: "Wheat", dairy: false, sesame: false, wheat: true, soy: false, egg: false, fish: false },
    { item: "Traditional Hummus", allergens: "Sesame", dairy: false, sesame: true, wheat: false, soy: false, egg: false, fish: false },
    { item: "Crazy Feta®", allergens: "Dairy", dairy: true, sesame: false, wheat: false, soy: false, egg: false, fish: false },
    { item: "Cucumber Dill Tzatziki", allergens: "Dairy", dairy: true, sesame: false, wheat: false, soy: false, egg: false, fish: false }
  ],

  // FAQ Accordion Content
  faqs: [
    {
      q: "What is the best menu item at CAVA?",
      a: "The **Harissa Avocado Bowl** is CAVA's most consistently praised item, combining fiery harissa honey chicken, Crazy Feta®, hummus, fresh avocado, and hot harissa vinaigrette. For a simpler first order, the **Chicken + Rice Bowl** is the safest, most commonly recommended baseline pick."
    },
    {
      q: "Is CAVA basically Chipotle?",
      a: "CAVA follows the same build-your-own, assembly-line format as Chipotle, which is why it's often nicknamed the 'Mediterranean Chipotle'. However, the cuisine is authentic Mediterranean, and CAVA's signature advantage is **six scratch-made dips included free** with every bowl or pita, whereas competitors charge extra for dips/guacamole."
    },
    {
      q: "Why is CAVA restaurant so expensive?",
      a: "CAVA bowls run $11 to $17, slightly above fast food, because every bowl includes premium scratch-made dips free, high-quality proteins like salmon, steak, and braised lamb, plus locally baked sprouted grain flatbread from Damascus Bakery in Brooklyn."
    },
    {
      q: "Is CAVA food actually healthy?",
      a: "Most CAVA bowls fall between **480 and 860 calories with 30g to 50g of protein**, putting it far ahead of typical fast-casual chains. Note that CAVA cooks with a blend of sunflower oil and olive oil across most ingredients. Keeping your dressing on the side and choosing greens keeps meals easily under 600 calories."
    },
    {
      q: "Does CAVA have a secret menu?",
      a: "CAVA does not have an official secret menu published or endorsed by the company. Customers do create custom combinations using the 5-step builder, but nothing outside the standard ingredient roster is officially offered."
    },
    {
      q: "Can I order CAVA online and get student discounts?",
      a: "Yes! You can order directly via the CAVA App or cava.com to skip the line and earn CAVA Rewards. CAVA also offers a **10% Student Discount** Monday through Thursday with a valid .edu email verification in the app."
    },
    {
      q: "Does CAVA offer gluten-free options?",
      a: "Yes! Every single bowl is 100% gluten-free when built without pita bread or pita crisps. All bases, proteins, and dips are naturally gluten-free. Always notify staff if you have celiac disease due to shared counter preparation."
    }
  ],

  // CAVA Signature Sauces & Dressings
  sauces: [
    {
      id: "sauce-hot-harissa",
      name: "Hot Harissa Vinaigrette",
      heat: "🔥🔥🔥 Hot",
      calories: 110,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      flavor: "Spicy, tangy, smoked red pepper with garlic kick",
      bestWith: "Harissa Honey Chicken, Steak, Brown Rice",
      icon: "🌶️"
    },
    {
      id: "sauce-lemon-tahini",
      name: "Lemon Herb Tahini",
      heat: "Mild & Creamy",
      calories: 100,
      dietary: ["vegan", "gluten-free"],
      allergens: ["Sesame"],
      flavor: "Nutty roasted sesame paste, fresh squeezed lemon, minced parsley",
      bestWith: "Falafel, SuperGreens, Black Lentils",
      icon: "🍋"
    },
    {
      id: "sauce-tahini-caesar",
      name: "Sesame Tahini Caesar",
      heat: "Savory & Rich",
      calories: 130,
      dietary: ["vegetarian"],
      allergens: ["Sesame", "Dairy"],
      flavor: "Creamy parmesan, cracked black pepper, garlic & toasted sesame",
      bestWith: "Grilled Chicken, Romaine, Parmesan Crisps",
      icon: "🥣"
    },
    {
      id: "sauce-tzatziki",
      name: "Cucumber Dill Tzatziki",
      heat: "Cooling & Fresh",
      calories: 40,
      dietary: ["vegetarian", "gluten-free"],
      allergens: ["Dairy"],
      flavor: "Strained Greek yogurt, grated Persian cucumber, garlic, dill",
      bestWith: "Braised Lamb, Warm Pitas, Saffron Rice",
      icon: "🥒"
    },
    {
      id: "sauce-skhug",
      name: "Skhug (Chili Herb Sauce)",
      heat: "🔥🔥 Medium-Hot",
      calories: 80,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      flavor: "Yemenite cilantro, serrano chilies, coriander, cardamom, EVOO",
      bestWith: "Steak, Spicy Lamb Meatballs, RightRice™",
      icon: "🌿"
    },
    {
      id: "sauce-balsamic-date",
      name: "Balsamic Date Vinaigrette",
      heat: "Sweet & Tangy",
      calories: 130,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      flavor: "Pureed Medjool dates, aged balsamic vinegar, olive oil",
      bestWith: "Greek Salad, Baby Arugula, Roasted Veggies",
      icon: "🍇"
    },
    {
      id: "sauce-garlic",
      name: "Creamy Garlic Dressing",
      heat: "Savory & Punchy",
      calories: 140,
      dietary: ["vegetarian"],
      allergens: [],
      flavor: "Slow-emulsified roasted & fresh garlic, lemon, Mediterranean spices",
      bestWith: "Chicken Shawarma, Pitas, Roasted Sweet Potatoes",
      icon: "🧄"
    },
    {
      id: "sauce-greek-vinaigrette",
      name: "Classic Greek Herb Vinaigrette",
      heat: "Zesty & Light",
      calories: 120,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      flavor: "Red wine vinegar, Greek oregano, sumac, cold-pressed olive oil",
      bestWith: "SuperGreens + Grilled Chicken, Tomato Salad",
      icon: "🌿"
    }
  ],

  // CAVA Copycat At-Home Recipes
  recipes: [
    {
      id: "recipe-crazy-feta",
      title: "Copycat CAVA Crazy Feta®",
      prepTime: "10 mins",
      difficulty: "Easy",
      calories: "110 cal/serving",
      description: "CAVA's signature whipped jalapeño feta dip that regulars obsess over.",
      ingredients: [
        "8 oz high-quality block Greek Feta (in brine)",
        "2 fresh jalapeño peppers (charred over open flame)",
        "2 cloves garlic, minced",
        "3 tbsp Extra Virgin Olive Oil",
        "1 tbsp fresh lemon juice",
        "Pinch of dried Greek oregano"
      ],
      steps: [
        "Char the jalapeños over an open flame or broil until skins blister. Peel and deseed.",
        "Add feta, charred jalapeños, garlic, lemon juice, and olive oil to food processor.",
        "Pulse until creamy and fluffy with small green jalapeño specks.",
        "Chill for 30 minutes and serve with warm pita chips!"
      ],
      icon: "🧀"
    },
    {
      id: "recipe-harissa-chicken",
      title: "Copycat Harissa Honey Chicken",
      prepTime: "25 mins (Plus marinating)",
      difficulty: "Medium",
      calories: "240 cal/serving",
      description: "CAVA's #1 most ordered protein: juicy flame-grilled chicken with sweet-heat harissa glaze.",
      ingredients: [
        "1.5 lbs boneless chicken thighs or breast cutlets",
        "3 tbsp Mediterranean Harissa paste",
        "2 tbsp pure honey or maple syrup",
        "3 cloves garlic, crushed",
        "2 tbsp olive oil + 1 tbsp lemon juice",
        "1 tsp smoked paprika, 1 tsp cumin, sea salt"
      ],
      steps: [
        "Whisk harissa, honey, olive oil, garlic, lemon juice, and spices in a bowl.",
        "Coat chicken thoroughly and marinate in refrigerator for at least 2 hours.",
        "Grill in a cast-iron skillet or outdoor grill over medium-high heat for 6-8 mins per side.",
        "Rest 5 minutes, slice into bite-sized strips, and layer over grain bowls!"
      ],
      icon: "🍗"
    },
    {
      id: "recipe-saffron-rice",
      title: "Copycat Saffron Basmati Rice",
      prepTime: "20 mins",
      difficulty: "Easy",
      calories: "190 cal/serving",
      description: "Fluffy, aromatic golden basmati rice that serves as the foundation for CAVA bowls.",
      ingredients: [
        "1.5 cups long-grain white Basmati rice (rinsed)",
        "2.5 cups vegetable or chicken broth",
        "1 pinch saffron threads (steeped in 2 tbsp warm water)",
        "1/2 tsp ground turmeric (for golden color)",
        "1 tbsp olive oil or butter, sea salt"
      ],
      steps: [
        "Rinse basmati rice until water runs clear.",
        "In a saucepan, heat olive oil, toast turmeric and rinsed rice for 1 minute.",
        "Pour in broth and saffron water. Bring to a boil, then cover and reduce to low heat.",
        "Simmer 15 minutes, remove from heat, let steam 5 minutes, and fluff with a fork."
      ],
      icon: "🍚"
    }
  ],

  promoCodes: {
    "CAVALOVER15": { discountPercent: 15, description: "15% off your Mediterranean feast" },
    "FRESH20": { discountPercent: 20, description: "20% off orders over $25" },
    "TASTECAVA": { discountAmount: 5.00, description: "$5.00 off welcome reward" },
    "STUDENT10": { discountPercent: 10, description: "10% off Student Special (Mon-Thu)" }
  },

  locations: [
    { id: "loc-1", name: "CAVA Downtown Metropolis", address: "450 Grand Avenue, Suite 102", distance: "0.8 miles", status: "Open Now", hours: "10:45 AM – 10:00 PM (7 Days)", readyIn: "15-20 min" },
    { id: "loc-2", name: "CAVA Bethesda Original", address: "7800 Wisconsin Ave, Bethesda MD", distance: "Historic Flagship", status: "Open Now", hours: "10:45 AM – 10:00 PM", readyIn: "10-15 min" },
    { id: "loc-3", name: "CAVA Midtown Plaza", address: "780 Lexington Blvd", distance: "2.1 miles", status: "Open Now", hours: "10:45 AM – 10:00 PM", readyIn: "20-25 min" }
  ]
};

