// ==========================================================================
// CAVA Menu 2026 � Complete Dataset, Builder, Nutrition & Editorial Content
// Verified against CAVA Group SEC Filings & Official Published Nutrition
// ==========================================================================

export const MENU_DATA = {
  meta: {
    title: "CAVA Menu 2026 � Prices, Calories & Full Mediterranean Food Guide",
    reviewDate: "April 2026",
    totalLocations: "459+",
    totalStates: "29 States + Washington, D.C.",
    ticker: "NYSE: CAVA",
    verifiedBy: "Menu Content Specialist & Editorial Review Team"
  },

  categories: [
    { id: "all", label: "All Items", icon: "?" },
    { id: "in-season", label: "In Season", icon: "??" },
    { id: "build-your-own", label: "Build Your Own", icon: "??" },
    { id: "bowls", label: "Bowls", icon: "??" },
    { id: "pitas", label: "Pita", icon: "??" },
    { id: "sides", label: "Sides", icon: "??" },
    { id: "kids-meal", label: "Kids Meal", icon: "??" },
    { id: "drinks", label: "Drinks", icon: "??" },
    { id: "desserts", label: "Desserts", icon: "??" }
  ],

  items: [
    {
      id: "greens-grains-bowl",
      name: "Greens + Grains Bowl",
      category: "bowls",
      price: 11.75,
      priceRange: "",
      calories: 310,
      calorieRange: "310-1190 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Mix and match your favorite greens and grains to build a bowl just the way you like it.",
      ingredients: [],
      image: "img/greens-grains-bowl.webp",
      icon: "✨"
    },
    {
      id: "grains-bowl",
      name: "Grains Bowl",
      category: "bowls",
      price: 11.75,
      priceRange: "",
      calories: 435,
      calorieRange: "435-1330 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Choose your grain bowl base: saffron basmati rice, brown basmati rice, or black lentils.",
      ingredients: [],
      image: "img/grains-bowl.webp",
      icon: "✨"
    },
    {
      id: "salad-bowl",
      name: "Salad Bowl",
      category: "bowls",
      price: 11.75,
      priceRange: "",
      calories: 185,
      calorieRange: "185-1055 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Choose your greens to start building your bowl: arugula, baby spinach, romaine, Super Greens, or Power Greens.",
      ingredients: [],
      image: "img/salad-bowl.webp",
      icon: "✨"
    },
    {
      id: "chicken-rice",
      name: "Chicken + Rice",
      category: "bowls",
      price: 11.75,
      priceRange: "",
      calories: 700,
      calorieRange: "700 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"], "high-protein",
      allergens: [],
      description: "Grilled chicken, hummus, tzatziki, pickled onions, tomato + onion, cucumber, feta, arugula, brown rice, Greek vinaigrette",
      ingredients: [],
      image: "img/chicken-rice.webp",
      icon: "✨"
    },
    {
      id: "harissa-avocado",
      name: "Harissa Avocado",
      category: "bowls",
      price: 16.25,
      priceRange: "",
      calories: 830,
      calorieRange: "830 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Harissa honey chicken, Crazy Feta®, hummus, avocado, corn, cucumber, feta, pickled onions, basmati rice, Super Greens, harissa vinaigrette",
      ingredients: [],
      image: "img/harissa-avocado.webp",
      icon: "✨"
    },
    {
      id: "steak-harissa",
      name: "Steak + Harissa",
      category: "bowls",
      price: 15.45,
      priceRange: "",
      calories: 620,
      calorieRange: "620 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"], "high-protein",
      allergens: [],
      description: "Grilled steak, Crazy Feta®, red pepper hummus, tomato + onion, cucumber, feta, sumac cabbage slaw, brown rice, Super Greens, harissa vinaigrette",
      ingredients: [],
      image: "img/steak-harissa.webp",
      icon: "✨"
    },
    {
      id: "greek-salad",
      name: "Greek Salad",
      category: "bowls",
      price: 11.75,
      priceRange: "",
      calories: 580,
      calorieRange: "580 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Grilled chicken, tzatziki, hummus, feta, tomato + onion, cucumber, olives, romaine, arugula, Greek vinaigrette",
      ingredients: [],
      image: "img/greek-salad.webp",
      icon: "✨"
    },
    {
      id: "falafel-crunch",
      name: "
      category: "bowls",
      price: 11.75,
      priceRange: "",
      calories: 860,
      calorieRange: "860 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      ",$2dietary: ["vegetarian", "vegan"],
      allergens: [],
      description: "Half falafel, half roasted veggies, hummus, Crazy Feta®, cucumber, sumac cabbage slaw, romaine, pickled onions, tomato + onion, pita crisps, rice, lentils, skhug",
      ingredients: [],
      image: "img/falafel-crunch.webp",
      icon: "✨"
    },
    {
      id: "spicy-lamb-avocado",
      name: "Spicy Lamb + Avocado",
      category: "bowls",
      price: 17.05,
      priceRange: "",
      calories: 800,
      calorieRange: "800 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Spicy lamb meatballs, avocado, Crazy Feta®, red pepper hummus, pickled onions, cucumber, tomato + onion, Super Greens, lentils, lemon herb tahini",
      ingredients: [],
      image: "img/spicy-lamb-avocado.webp",
      icon: "✨"
    },
    {
      id: "strawberry-steak-salad",
      name: "Strawberry Steak Salad",
      category: "bowls",
      price: 15.45,
      priceRange: "",
      calories: 420,
      calorieRange: "420 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"], "high-protein",
      allergens: [],
      description: "Grilled steak, traditional hummus, red pepper hummus, fire-roasted corn, pickled onions, feta, Power Greens, strawberry sesame dressing",
      ingredients: [],
      image: "img/strawberry-steak-salad.webp",
      icon: "✨"
    },
    {
      id: "salmon-strawberry-sesame",
      name: "Salmon + Strawberry Sesame",
      category: "bowls",
      price: 16,
      priceRange: "",
      calories: 700,
      calorieRange: "700 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Glazed salmon, tzatziki, red pepper hummus, cucumber, feta, tomato + onion, sumac slaw, brown rice, spinach, and strawberry sesame dressing",
      ingredients: [],
      image: "img/salmon-strawberry-sesame.webp",
      icon: "✨"
    },
    {
      id: "salmon-yogurt-dill",
      name: "Salmon + Yogurt Dill",
      category: "bowls",
      price: 16,
      priceRange: "",
      calories: 710,
      calorieRange: "710 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Glazed salmon, Crazy Feta®, hummus, fire-roasted corn, tomato + onion, cucumber, rice, arugula, and yogurt dill dressing",
      ingredients: [],
      image: "img/salmon-yogurt-dill.webp",
      icon: "✨"
    },
    {
      id: "pomegranate-glazed-salmon",
      name: "Pomegranate Glazed Salmon",
      category: "bowls",
      price: 18.85,
      priceRange: "",
      calories: 1040,
      calorieRange: "1040 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Glazed salmon, Crazy Feta®, hummus, avocado, pickled onions, tomato + cucumber, fiery broccoli, saffron basmati rice, Greek vinaigrette",
      ingredients: [],
      image: "img/pomegranate-glazed-salmon.webp",
      icon: "✨"
    },
    {
      id: "pita",
      name: "Pita",
      category: "pitas",
      price: 11.75,
      priceRange: "",
      calories: 485,
      calorieRange: "485-1340 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Fill our fluffy and perfectly chewy pita with your unique combo of ingredients. Made with sprouted grains.",
      ingredients: [],
      image: "img/pita.webp",
      icon: "✨"
    },
    {
      id: "steak-feta",
      name: "Steak + Feta",
      category: "pitas",
      price: 15.45,
      priceRange: "",
      calories: 820,
      calorieRange: "820 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"], "high-protein",
      allergens: [],
      description: "Grilled steak, Crazy Feta®, red pepper hummus, pickled onions, feta, pickles, romaine, garlic dressing, Greek vinaigrette, pita",
      ingredients: [],
      image: "img/steak-feta.webp",
      icon: "✨"
    },
    {
      id: "greek-chicken",
      name: "Greek Chicken",
      category: "pitas",
      price: 11.75,
      priceRange: "",
      calories: 720,
      calorieRange: "720 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"], "high-protein",
      allergens: [],
      description: "Grilled chicken, tzatziki, tomato + onion, olives, feta, romaine, yogurt dill dressing, pita",
      ingredients: [],
      image: "img/greek-chicken.webp",
      icon: "✨"
    },
    {
      id: "spicy-chicken-avocado",
      name: "Spicy Chicken + Avocado",
      category: "pitas",
      price: 16.25,
      priceRange: "",
      calories: 930,
      calorieRange: "930 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"], "high-protein",
      allergens: [],
      description: "Harissa honey chicken, Crazy Feta®, avocado, pickles, corn, feta, pickled onions, harissa vinaigrette, pita",
      ingredients: [],
      image: "img/spicy-chicken-avocado.webp",
      icon: "✨"
    },
    {
      id: "harissa-bbq-pita-chips",
      name: "Harissa BBQ Pita Chips",
      category: "sides",
      price: 2.75,
      priceRange: "",
      calories: 280,
      calorieRange: "280 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Barbecue meets the Mediterranean. Our classic pita chips mixed with a kick of cayenne and a blend of spices. A little spicy, a little smoky, and a tiny bit sweet.",
      ingredients: [],
      image: "img/harissa-bbq-pita-chips.webp",
      icon: "✨"
    },
    {
      id: "classic-pita-chips",
      name: "Classic Pita Chips",
      category: "sides",
      price: 2.75,
      priceRange: "",
      calories: 280,
      calorieRange: "280 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Made from our classic pitas. Cut, then fried for a deliciously dippable, chewy bite.",
      ingredients: [],
      image: "img/classic-pita-chips.webp",
      icon: "✨"
    },
    {
      id: "side-pita",
      name: "Side Pita",
      category: "sides",
      price: 2.45,
      priceRange: "",
      calories: 320,
      calorieRange: "320 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Our fluffy and perfectly chewy pita made with sprouted grains.",
      ingredients: [],
      image: "img/side-pita.webp",
      icon: "✨"
    },
    {
      id: "side-crazy-feta",
      name: "Side Crazy Feta®",
      category: "sides",
      price: 4.15,
      priceRange: "",
      calories: 210,
      calorieRange: "210 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Feta whipped with jalapeño, onion, and olive oil for just that right level of spicy. A CAVA signature.",
      ingredients: [],
      image: "img/side-crazy-feta.webp",
      icon: "✨"
    },
    {
      id: "side-hummus",
      name: "Side Hummus",
      category: "sides",
      price: 3.45,
      priceRange: "",
      calories: 140,
      calorieRange: "140 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Chickpeas puréed with tahini, lemon juice, fresh garlic, salt. A guest favorite and CAVA classic.",
      ingredients: [],
      image: "img/side-hummus.webp",
      icon: "✨"
    },
    {
      id: "side-harissa",
      name: "Side Harissa",
      category: "sides",
      price: 3.45,
      priceRange: "",
      calories: 220,
      calorieRange: "220 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Fiery, tomato-forward, and full of spices.",
      ingredients: [],
      image: "img/side-harissa.webp",
      icon: "✨"
    },
    {
      id: "side-tzatziki",
      name: "Side Tzatziki",
      category: "sides",
      price: 3.45,
      priceRange: "",
      calories: 100,
      calorieRange: "100 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Made with Greek yogurt, shredded cucumber, and dill. Thick and creamy.",
      ingredients: [],
      image: "img/side-tzatziki.webp",
      icon: "✨"
    },
    {
      id: "side-red-pepper-hummus",
      name: "Side Red Pepper Hummus",
      category: "sides",
      price: 3.45,
      priceRange: "",
      calories: 110,
      calorieRange: "110 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Roasted red peppers puréed with chickpeas, tahini, and garlic.",
      ingredients: [],
      image: "img/side-red-pepper-hummus.webp",
      icon: "✨"
    },
    {
      id: "side-roasted-eggplant",
      name: "Side Roasted Eggplant",
      category: "sides",
      price: 3.65,
      priceRange: "",
      calories: 150,
      calorieRange: "150 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Roasted eggplant blended with lemon juice, parsley, onions, and garlic.",
      ingredients: [],
      image: "img/side-roasted-eggplant.webp",
      icon: "✨"
    },
    {
      id: "kids-meal",
      name: "Kids Meal",
      category: "kids-meal",
      price: 7.45,
      priceRange: "",
      calories: 335,
      calorieRange: "335-1130 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "A kid-sized, build-your-own meal with a half-serving of one main + grain, one dip, one dressing, and up to three toppings. Choose three classic pita chips or a side 1/4 pita, and small juice or milk.",
      ingredients: [],
      image: "img/kids-meal.webp",
      icon: "✨"
    },
    {
      id: "strawberry-ginger",
      name: "Strawberry Ginger",
      category: "drinks",
      price: 3.35,
      priceRange: "$3.35 (Small) / $3.75 (Large)",
      calories: 150,
      calorieRange: "150 Cal (Small) / 210 Cal (Large)",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "A strawberry + raspberry drink with a hint of lively ginger to keep things interesting.",
      ingredients: [],
      image: "img/strawberry-ginger.webp",
      icon: "✨"
    },
    {
      id: "blueberry-lavender",
      name: "Blueberry Lavender",
      category: "drinks",
      price: 3.35,
      priceRange: "$3.35 (Small) / $3.75 (Large)",
      calories: 140,
      calorieRange: "140 Cal (Small) / 190 Cal (Large)",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Made in-house from a purée of blueberries and lavender.",
      ingredients: [],
      image: "img/blueberry-lavender.webp",
      icon: "✨"
    },
    {
      id: "cucumber-mint-lime",
      name: "Cucumber Mint Lime",
      category: "drinks",
      price: 3.35,
      priceRange: "$3.35 (Small) / $3.75 (Large)",
      calories: 180,
      calorieRange: "180 Cal (Small) / 240 Cal (Large)",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Sweet and cooling, balanced out with fresh lime juice. Made in-house.",
      ingredients: [],
      image: "img/cucumber-mint-lime.webp",
      icon: "✨"
    },
    {
      id: "classic-lemonade",
      name: "Classic Lemonade",
      category: "drinks",
      price: 3.35,
      priceRange: "$3.35 (Small) / $3.75 (Large)",
      calories: 260,
      calorieRange: "260 Cal (Small) / 360 Cal (Large)",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "A sweet and refreshing lemonade made in-house.",
      ingredients: [],
      image: "img/classic-lemonade.webp",
      icon: "✨"
    },
    {
      id: "unsweet-tea",
      name: "Unsweet Tea",
      category: "drinks",
      price: 3.35,
      priceRange: "$3.35 (Small) / $3.75 (Large)",
      calories: 0,
      calorieRange: "0 Cal (Small) / 0 Cal (Large)",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Unsweetened iced black tea with a balanced, smooth taste. Brewed in-house.",
      ingredients: [],
      image: "img/unsweet-tea.webp",
      icon: "✨"
    },
    {
      id: "sweet-tea",
      name: "Sweet Tea",
      category: "drinks",
      price: 3.35,
      priceRange: "$3.35 (Small) / $3.75 (Large)",
      calories: 150,
      calorieRange: "150 Cal (Small) / 200 Cal (Large)",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Sweetened black tea brewed in-house.",
      ingredients: [],
      image: "img/sweet-tea.jpg",
      icon: "✨"
    },
    {
      id: "fountain-soda",
      name: "Fountain Soda",
      category: "drinks",
      price: 3.35,
      priceRange: "$3.35 (Small) / $3.75 (Large)",
      calories: 190,
      calorieRange: "190 Cal (Small) / 270 Cal (Large)",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Choose from a selection of Maine Root fountain sodas.",
      ingredients: [],
      image: "img/fountain-soda.webp",
      icon: "✨"
    },
    {
      id: "spindrift-lemon",
      name: "Spindrift Lemon",
      category: "drinks",
      price: 2.95,
      priceRange: "",
      calories: 3,
      calorieRange: "3 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Sparkling lemon water.",
      ingredients: [],
      image: "img/spindrift-lemon.webp",
      icon: "✨"
    },
    {
      id: "spindrift-half-tea-half-lemon",
      name: "Spindrift Half Tea & Half Lemon",
      category: "drinks",
      price: 2.95,
      priceRange: "",
      calories: 5,
      calorieRange: "5 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Sparkling half tea, half lemon water.",
      ingredients: [],
      image: "img/spindrift-half-tea-half-lemon.webp",
      icon: "✨"
    },
    {
      id: "open-water-still",
      name: "Open Water Still",
      category: "drinks",
      price: 2.95,
      priceRange: "",
      calories: 0,
      calorieRange: "0 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Open Water still water.",
      ingredients: [],
      image: "img/open-water-still.webp",
      icon: "✨"
    },
    {
      id: "open-water-sparkling",
      name: "Open Water Sparkling",
      category: "drinks",
      price: 2.95,
      priceRange: "",
      calories: 0,
      calorieRange: "0 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Open Water sparkling water.",
      ingredients: [],
      image: "img/open-water-sparkling.webp",
      icon: "✨"
    },
    {
      id: "kids-apple-juice",
      name: "Kids Apple Juice",
      category: "drinks",
      price: 2.55,
      priceRange: "",
      calories: 35,
      calorieRange: "35 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Organic apple juice from Honest Kids. No sugar added.",
      ingredients: [],
      image: "img/kids-apple-juice.jpg",
      icon: "✨"
    },
    {
      id: "kids-milk",
      name: "Kids Milk",
      category: "drinks",
      price: 2.55,
      priceRange: "",
      calories: 110,
      calorieRange: "110 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Organic 1% milk.",
      ingredients: [],
      image: "img/kids-milk.webp",
      icon: "✨"
    },
    {
      id: "kids-chocolate-milk",
      name: "Kids Chocolate Milk",
      category: "drinks",
      price: 2.55,
      priceRange: "",
      calories: 150,
      calorieRange: "150 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "Organic 1% chocolate milk.",
      ingredients: [],
      image: "img/kids-chocolate-milk.webp",
      icon: "✨"
    },
    {
      id: "salted-chocolate-oat-cookie",
      name: "Salted Chocolate Oat Cookie",
      category: "desserts",
      price: 3.35,
      priceRange: "",
      calories: 240,
      calorieRange: "240 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "If an oatmeal cookie and a salted chocolate chip cookie had a baby.",
      ingredients: [],
      image: "img/salted-chocolate-oat-cookie.jpg",
      icon: "✨"
    },
    {
      id: "greyston-blondie",
      name: "Greyston Blondie",
      category: "desserts",
      price: 2.75,
      priceRange: "",
      calories: 140,
      calorieRange: "140 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "A blondie with a super soft, almost gooey inside.",
      ingredients: [],
      image: "img/greyston-blondie.webp",
      icon: "✨"
    },
    {
      id: "greyston-brownie",
      name: "Greyston Brownie",
      category: "desserts",
      price: 2.75,
      priceRange: "",
      calories: 150,
      calorieRange: "150 Cal",
      protein: "",
      carbs: "",
      fat: "",
      badge: "",
      isTrending: false,
      dietary: ["high-protein", "gluten-free"],
      allergens: [],
      description: "An intensely chocolatey brownie, with a fudgy, almost gooey inside.",
      ingredients: [],
      image: "img/greyston-brownie.webp",
      icon: "✨"
    }
  ],

  // 5-Step Build Your Own Bowl Configurator Options
  builder: {
    basePrice: 12.95,
    steps: [
      {
        stepId: 1,
        title: "Step 1: Choose Your Base",
        subtitle: "Pick up to 2 bases for your foundation (Calorie impact: 20 � 310 cal)",
        maxSelect: 2,
        required: true,
        options: [
          { id: "supergreens", name: "SuperGreens (Kale, Spinach, Romaine)", calories: 25, protein: 2, carbs: 4, fat: 0, tags: ["vegan", "gluten-free", "low-cal"], icon: "??" },
          { id: "arugula-romaine", name: "Baby Arugula & Romaine", calories: 20, protein: 2, carbs: 3, fat: 0, tags: ["vegan", "gluten-free", "low-cal"], icon: "??" },
          { id: "saffron-rice", name: "Saffron Basmati Rice", calories: 190, protein: 4, carbs: 40, fat: 2, tags: ["vegan", "gluten-free"], icon: "??" },
          { id: "brown-rice", name: "Wild Brown Rice", calories: 170, protein: 4, carbs: 36, fat: 1.5, tags: ["vegan", "gluten-free"], icon: "??" },
          { id: "black-lentils", name: "Black Lentils (+18g Protein, +15g Fiber)", calories: 180, protein: 18, carbs: 32, fat: 1, tags: ["vegan", "high-protein", "gluten-free"], icon: "??" },
          { id: "right-rice", name: "RightRice� (High Protein Veggie Rice)", calories: 160, protein: 10, carbs: 28, fat: 1, tags: ["vegan", "high-protein", "gluten-free"], icon: "??" }
        ]
      },
      {
        stepId: 2,
        title: "Step 2: Pick Your Protein",
        subtitle: "Select 1 of 8 proteins (Or double up for +$3.50)",
        maxSelect: 1,
        required: true,
        options: [
          { id: "grilled-chicken", name: "Grilled Chicken Breast (28-33g protein)", calories: 200, protein: 34, carbs: 0, fat: 6, extraCost: 0, tags: ["high-protein", "gluten-free"], icon: "??" },
          { id: "harissa-honey-chicken", name: "Harissa Honey Chicken (#1 Most Ordered)", calories: 240, protein: 32, carbs: 6, fat: 9, extraCost: 0, tags: ["high-protein"], icon: "??" },
          { id: "grilled-steak", name: "Grilled Marinated Steak", calories: 260, protein: 31, carbs: 1, fat: 14, extraCost: 1.50, tags: ["high-protein", "gluten-free"], icon: "??" },
          { id: "braised-lamb", name: "Slow-Roasted Braised Lamb", calories: 290, protein: 30, carbs: 2, fat: 18, extraCost: 1.50, tags: ["high-protein"], icon: "??" },
          { id: "spicy-lamb-meatballs", name: "Spicy Lamb Meatballs", calories: 270, protein: 28, carbs: 4, fat: 16, extraCost: 1.50, tags: ["high-protein"], icon: "??" },
          { id: "glazed-salmon", name: "Glazed Wild Salmon (2026 Special)", calories: 280, protein: 32, carbs: 4, fat: 15, extraCost: 3.25, tags: ["high-protein", "gluten-free"], icon: "??" },
          { id: "golden-falafel", name: "Golden Crisp Falafel (Plant-Based)", calories: 220, protein: 9, carbs: 24, fat: 11, extraCost: 0, tags: ["vegan", "vegetarian"], allergen: "Sesame", icon: "??" },
          { id: "roasted-veggies", name: "Roasted Medley Vegetables", calories: 110, protein: 4, carbs: 18, fat: 3, extraCost: 0, tags: ["vegan", "gluten-free"], icon: "??" }
        ]
      },
      {
        stepId: 3,
        title: "Step 3: Add Dips & Spreads (Up to 3 Free)",
        subtitle: "All 6 scratch-made dips are included free with every bowl",
        maxSelect: 3,
        required: true,
        options: [
          { id: "crazy-feta", name: "Crazy Feta� (Whipped Feta & Jalape�o)", calories: 110, protein: 4, carbs: 2, fat: 9, tags: ["vegetarian"], allergen: "Dairy", icon: "??" },
          { id: "traditional-hummus", name: "Traditional Silky Hummus", calories: 90, protein: 3, carbs: 9, fat: 5, tags: ["vegan", "gluten-free"], allergen: "Sesame", icon: "??" },
          { id: "red-pepper-hummus", name: "Roasted Red Pepper Hummus", calories: 95, protein: 3, carbs: 10, fat: 5, tags: ["vegan", "gluten-free"], allergen: "Sesame", icon: "???" },
          { id: "tzatziki", name: "Cucumber Dill Tzatziki", calories: 40, protein: 2, carbs: 2, fat: 2.5, tags: ["vegetarian", "gluten-free"], allergen: "Dairy", icon: "??" },
          { id: "roasted-eggplant", name: "Roasted Eggplant Dip", calories: 45, protein: 1, carbs: 5, fat: 2.5, tags: ["vegan", "gluten-free", "low-cal"], icon: "??" },
          { id: "harissa", name: "Fiery Harissa Paste", calories: 50, protein: 1, carbs: 3, fat: 4, tags: ["vegan", "gluten-free"], icon: "??" }
        ]
      },
      {
        stepId: 4,
        title: "Step 4: Load Up on Toppings (Unlimited Free)",
        subtitle: "No upcharge! Best way to add crunch, fiber, and flavor",
        maxSelect: 7,
        required: false,
        options: [
          { id: "fire-roasted-corn", name: "Fire-Roasted Corn", calories: 35, protein: 1, carbs: 7, fat: 0.5, tags: ["vegan"], icon: "??" },
          { id: "pickled-onions", name: "Pickled Red Onions", calories: 15, protein: 0, carbs: 3, fat: 0, tags: ["vegan"], icon: "??" },
          { id: "crumbled-feta", name: "Greek Crumbled Feta", calories: 60, protein: 4, carbs: 1, fat: 5, tags: ["vegetarian"], allergen: "Dairy", icon: "??" },
          { id: "kalamata-olives", name: "Kalamata Olives", calories: 50, protein: 0, carbs: 2, fat: 5, tags: ["vegan"], icon: "??" },
          { id: "persian-cucumbers", name: "Diced Persian Cucumbers", calories: 10, protein: 0, carbs: 2, fat: 0, tags: ["vegan"], icon: "??" },
          { id: "tomato-cucumber", name: "Tomato + Cucumber Salad", calories: 20, protein: 1, carbs: 4, fat: 0, tags: ["vegan"], icon: "??" },
          { id: "fiery-broccoli", name: "Fiery Charred Broccoli", calories: 45, protein: 3, carbs: 6, fat: 1.5, tags: ["vegan"], icon: "??" },
          { id: "pita-crisps", name: "House-Baked Pita Crisps", calories: 70, protein: 2, carbs: 12, fat: 2, tags: ["vegan"], allergen: "Wheat", icon: "??" },
          { id: "fresh-avocado", name: "Fresh Sliced Avocado", calories: 120, protein: 2, carbs: 6, fat: 10, extraCost: 1.95, tags: ["vegan", "gluten-free"], icon: "??" }
        ]
      },
      {
        stepId: 5,
        title: "Step 5: Finish With Dressing (1 Included Free)",
        subtitle: "Tie all flavors together (Tip: ask on side to save calories)",
        maxSelect: 2,
        required: true,
        options: [
          { id: "greek-vinaigrette", name: "Classic Greek Herb Vinaigrette", calories: 120, protein: 0, carbs: 2, fat: 12, tags: ["vegan"], icon: "??" },
          { id: "lemon-herb-tahini", name: "Lemon Herb Tahini", calories: 100, protein: 2, carbs: 4, fat: 9, tags: ["vegan"], allergen: "Sesame", icon: "??" },
          { id: "hot-harissa-vinaigrette", name: "Hot Harissa Vinaigrette", calories: 110, protein: 0, carbs: 4, fat: 10, tags: ["vegan"], icon: "???" },
          { id: "yogurt-dill", name: "Yogurt Dill Dressing", calories: 70, protein: 2, carbs: 3, fat: 5, tags: ["vegetarian"], allergen: "Dairy", icon: "??" },
          { id: "skhug", name: "Skhug (Middle Eastern Herb & Chili)", calories: 80, protein: 1, carbs: 2, fat: 8, tags: ["vegan"], icon: "??" },
          { id: "balsamic-date", name: "Balsamic Date Vinaigrette", calories: 130, protein: 0, carbs: 8, fat: 11, tags: ["vegan"], icon: "??" },
          { id: "garlic-dressing", name: "Creamy Garlic Dressing", calories: 140, protein: 1, carbs: 2, fat: 15, tags: ["vegetarian"], icon: "??" },
          { id: "tahini-caesar", name: "Sesame Tahini Caesar", calories: 130, protein: 2, carbs: 3, fat: 13, tags: ["vegetarian"], allergen: "Sesame", icon: "??" }
        ]
      }
    ]
  },

  // Calorie-ranked table from lowest to highest
  calorieRankings: [
    { rank: 1, name: "SuperGreens + Grilled Chicken Bowl", calories: "480 cal", protein: "33g", carbs: "18g", fat: "22g", category: "Bowl", note: "Lowest calorie count, highest protein density" },
    { rank: 2, name: "Tahini Caesar Bowl", calories: "550 � 660 cal", protein: "42g", carbs: "28g", fat: "34g", category: "Bowl", note: "Savory & low carb if pita crisps reduced" },
    { rank: 3, name: "Greek Salad Bowl", calories: "585 � 600 cal", protein: "34g", carbs: "26g", fat: "32g", category: "Bowl", note: "Light & refreshing classic" },
    { rank: 4, name: "Garlicky Chicken Shawarma Bowl", calories: "600 � 660 cal", protein: "39g", carbs: "44g", fat: "28g", category: "Bowl", note: "Robust garlic & herb notes" },
    { rank: 5, name: "Keto Greens + Steak Bowl", calories: "615 cal", protein: "40g", carbs: "14g", fat: "42g", category: "Bowl", note: "Clean keto macro ratio" },
    { rank: 6, name: "Steak + Harissa Bowl", calories: "615 cal", protein: "41g", carbs: "38g", fat: "32g", category: "Bowl", note: "High protein, spicy kick" },
    { rank: 7, name: "Crispy Falafel Pita Pocket", calories: "620 cal", protein: "22g", carbs: "78g", fat: "26g", category: "Pita", note: "100% vegetarian staple" },
    { rank: 8, name: "Lemon Herb Chicken Bowl", calories: "650 cal", protein: "38g", carbs: "50g", fat: "26g", category: "Bowl", note: "Zesty & balanced" },
    { rank: 9, name: "Salmon + Strawberry Sesame Bowl", calories: "700 cal", protein: "37g", carbs: "52g", fat: "36g", category: "Bowl", note: "2026 limited-time seafood item" },
    { rank: 10, name: "Salmon + Yogurt Dill Bowl", calories: "710 cal", protein: "38g", carbs: "48g", fat: "38g", category: "Bowl", note: "2026 chef curation with wild salmon" },
    { rank: 11, name: "Chicken + Rice Bowl", calories: "710 � 715 cal", protein: "42g", carbs: "64g", fat: "28g", category: "Bowl", note: "Safest pick for first-time visitors" },
    { rank: 12, name: "Greek Chicken Pita", calories: "720 cal", protein: "38g", carbs: "62g", fat: "32g", category: "Pita", note: "Portable Mediterranean wrap" },
    { rank: 13, name: "Spicy Lamb + Avocado Bowl", calories: "780 � 795 cal", protein: "44g", carbs: "54g", fat: "44g", category: "Bowl", note: "Hearty and rich spiced meatballs" },
    { rank: 14, name: "Harissa Avocado Bowl", calories: "810 � 885 cal", protein: "38g", carbs: "68g", fat: "42g", category: "Bowl", note: "#1 most popular item on menu" },
    { rank: 15, name: "Steak + Feta Pita", calories: "810 cal", protein: "42g", carbs: "58g", fat: "38g", category: "Pita", note: "Hearty wrapped steak" },
    { rank: 16, name: "Falafel Crunch Bowl", calories: "860 cal", protein: "24g", carbs: "92g", fat: "38g", category: "Bowl", note: "High carb & high fiber plant bowl" },
    { rank: 17, name: "Spicy Chicken + Avocado Pita", calories: "970 � 1,030 cal", protein: "46g", carbs: "74g", fat: "48g", category: "Pita", note: "Loaded pita wrap, highest calorie build" }
  ],

  // Full Allergen Matrix Table
  allergensTable: [
    { item: "Harissa Avocado Bowl", allergens: "Sesame, Dairy", dairy: true, sesame: true, wheat: false, soy: false, egg: false, fish: false },
    { item: "Chicken + Rice Bowl", allergens: "Dairy, Wheat (if pita crisps added)", dairy: true, sesame: false, wheat: true, soy: false, egg: false, fish: false },
    { item: "Falafel Crunch Bowl", allergens: "Wheat, Sesame", dairy: false, sesame: true, wheat: true, soy: false, egg: false, fish: false },
    { item: "Greek Salad Bowl", allergens: "Dairy", dairy: true, sesame: false, wheat: false, soy: false, egg: false, fish: false },
    { item: "Steak + Harissa Bowl", allergens: "Dairy, Sesame", dairy: true, sesame: true, wheat: false, soy: false, egg: false, fish: false },
    { item: "Salmon + Strawberry Bowl", allergens: "Fish (Salmon), Sesame", dairy: false, sesame: true, wheat: false, soy: false, egg: false, fish: true },
    { item: "Spicy Chicken + Avocado Pita", allergens: "Dairy, Wheat, Sesame", dairy: true, sesame: true, wheat: true, soy: false, egg: false, fish: false },
    { item: "Tahini Caesar Bowl", allergens: "Dairy, Sesame, Wheat", dairy: true, sesame: true, wheat: true, soy: false, egg: false, fish: false },
    { item: "Pita Bread / Pita Chips", allergens: "Wheat", dairy: false, sesame: false, wheat: true, soy: false, egg: false, fish: false },
    { item: "Traditional Hummus", allergens: "Sesame", dairy: false, sesame: true, wheat: false, soy: false, egg: false, fish: false },
    { item: "Crazy Feta�", allergens: "Dairy", dairy: true, sesame: false, wheat: false, soy: false, egg: false, fish: false },
    { item: "Cucumber Dill Tzatziki", allergens: "Dairy", dairy: true, sesame: false, wheat: false, soy: false, egg: false, fish: false }
  ],

  // FAQ Accordion Content
  faqs: [
    {
      q: "What is the best menu item at CAVA?",
      a: "The **Harissa Avocado Bowl** is CAVA's most consistently praised item, combining fiery harissa honey chicken, Crazy Feta�, hummus, fresh avocado, and hot harissa vinaigrette. For a simpler first order, the **Chicken + Rice Bowl** is the safest, most commonly recommended baseline pick."
    },
    {
      q: "Is CAVA basically Chipotle?",
      a: "CAVA follows the same build-your-own, assembly-line format as Chipotle, which is why it's often nicknamed the 'Mediterranean Chipotle'. However, the cuisine is authentic Mediterranean, and CAVA's signature advantage is **six scratch-made dips included free** with every bowl or pita, whereas competitors charge extra for dips/guacamole."
    },
    {
      q: "Why is CAVA restaurant so expensive?",
      a: "CAVA bowls run $11 to $17, slightly above fast food, because every bowl includes premium scratch-made dips free, high-quality proteins like salmon, steak, and braised lamb, plus locally baked sprouted grain flatbread from Damascus Bakery in Brooklyn."
    },
    {
      q: "Is CAVA food actually healthy?",
      a: "Most CAVA bowls fall between **480 and 860 calories with 30g to 50g of protein**, putting it far ahead of typical fast-casual chains. Note that CAVA cooks with a blend of sunflower oil and olive oil across most ingredients. Keeping your dressing on the side and choosing greens keeps meals easily under 600 calories."
    },
    {
      q: "Does CAVA have a secret menu?",
      a: "CAVA does not have an official secret menu published or endorsed by the company. Customers do create custom combinations using the 5-step builder, but nothing outside the standard ingredient roster is officially offered."
    },
    {
      q: "Can I order CAVA online and get student discounts?",
      a: "Yes! You can order directly via the CAVA App or cava.com to skip the line and earn CAVA Rewards. CAVA also offers a **10% Student Discount** Monday through Thursday with a valid .edu email verification in the app."
    },
    {
      q: "Does CAVA offer gluten-free options?",
      a: "Yes! Every single bowl is 100% gluten-free when built without pita bread or pita crisps. All bases, proteins, and dips are naturally gluten-free. Always notify staff if you have celiac disease due to shared counter preparation."
    }
  ],

  // CAVA Signature Sauces & Dressings
  sauces: [
    {
      id: "sauce-hot-harissa",
      name: "Hot Harissa Vinaigrette",
      heat: "?????? Hot",
      calories: 110,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      flavor: "Spicy, tangy, smoked red pepper with garlic kick",
      bestWith: "Harissa Honey Chicken, Steak, Brown Rice",
      icon: "???"
    },
    {
      id: "sauce-lemon-tahini",
      name: "Lemon Herb Tahini",
      heat: "Mild & Creamy",
      calories: 100,
      dietary: ["vegan", "gluten-free"],
      allergens: ["Sesame"],
      flavor: "Nutty roasted sesame paste, fresh squeezed lemon, minced parsley",
      bestWith: "Falafel, SuperGreens, Black Lentils",
      icon: "??"
    },
    {
      id: "sauce-tahini-caesar",
      name: "Sesame Tahini Caesar",
      heat: "Savory & Rich",
      calories: 130,
      dietary: ["vegetarian"],
      allergens: ["Sesame", "Dairy"],
      flavor: "Creamy parmesan, cracked black pepper, garlic & toasted sesame",
      bestWith: "Grilled Chicken, Romaine, Parmesan Crisps",
      icon: "??"
    },
    {
      id: "sauce-tzatziki",
      name: "Cucumber Dill Tzatziki",
      heat: "Cooling & Fresh",
      calories: 40,
      dietary: ["vegetarian", "gluten-free"],
      allergens: ["Dairy"],
      flavor: "Strained Greek yogurt, grated Persian cucumber, garlic, dill",
      bestWith: "Braised Lamb, Warm Pitas, Saffron Rice",
      icon: "??"
    },
    {
      id: "sauce-skhug",
      name: "Skhug (Chili Herb Sauce)",
      heat: "???? Medium-Hot",
      calories: 80,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      flavor: "Yemenite cilantro, serrano chilies, coriander, cardamom, EVOO",
      bestWith: "Steak, Spicy Lamb Meatballs, RightRice�",
      icon: "??"
    },
    {
      id: "sauce-balsamic-date",
      name: "Balsamic Date Vinaigrette",
      heat: "Sweet & Tangy",
      calories: 130,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      flavor: "Pureed Medjool dates, aged balsamic vinegar, olive oil",
      bestWith: "Greek Salad, Baby Arugula, Roasted Veggies",
      icon: "??"
    },
    {
      id: "sauce-garlic",
      name: "Creamy Garlic Dressing",
      heat: "Savory & Punchy",
      calories: 140,
      dietary: ["vegetarian"],
      allergens: [],
      flavor: "Slow-emulsified roasted & fresh garlic, lemon, Mediterranean spices",
      bestWith: "Chicken Shawarma, Pitas, Roasted Sweet Potatoes",
      icon: "??"
    },
    {
      id: "sauce-greek-vinaigrette",
      name: "Classic Greek Herb Vinaigrette",
      heat: "Zesty & Light",
      calories: 120,
      dietary: ["vegan", "gluten-free"],
      allergens: [],
      flavor: "Red wine vinegar, Greek oregano, sumac, cold-pressed olive oil",
      bestWith: "SuperGreens + Grilled Chicken, Tomato Salad",
      icon: "??"
    }
  ],

  // CAVA Copycat At-Home Recipes
  recipes: [
    {
      id: "recipe-crazy-feta",
      title: "Copycat CAVA Crazy Feta�",
      prepTime: "10 mins",
      difficulty: "Easy",
      calories: "110 cal/serving",
      description: "CAVA's signature whipped jalape�o feta dip that regulars obsess over.",
      ingredients: [
        "8 oz high-quality block Greek Feta (in brine)",
        "2 fresh jalape�o peppers (charred over open flame)",
        "2 cloves garlic, minced",
        "3 tbsp Extra Virgin Olive Oil",
        "1 tbsp fresh lemon juice",
        "Pinch of dried Greek oregano"
      ],
      steps: [
        "Char the jalape�os over an open flame or broil until skins blister. Peel and deseed.",
        "Add feta, charred jalape�os, garlic, lemon juice, and olive oil to food processor.",
        "Pulse until creamy and fluffy with small green jalape�o specks.",
        "Chill for 30 minutes and serve with warm pita chips!"
      ],
      icon: "??"
    },
    {
      id: "recipe-harissa-chicken",
      title: "Copycat Harissa Honey Chicken",
      prepTime: "25 mins (Plus marinating)",
      difficulty: "Medium",
      calories: "240 cal/serving",
      description: "CAVA's #1 most ordered protein: juicy flame-grilled chicken with sweet-heat harissa glaze.",
      ingredients: [
        "1.5 lbs boneless chicken thighs or breast cutlets",
        "3 tbsp Mediterranean Harissa paste",
        "2 tbsp pure honey or maple syrup",
        "3 cloves garlic, crushed",
        "2 tbsp olive oil + 1 tbsp lemon juice",
        "1 tsp smoked paprika, 1 tsp cumin, sea salt"
      ],
      steps: [
        "Whisk harissa, honey, olive oil, garlic, lemon juice, and spices in a bowl.",
        "Coat chicken thoroughly and marinate in refrigerator for at least 2 hours.",
        "Grill in a cast-iron skillet or outdoor grill over medium-high heat for 6-8 mins per side.",
        "Rest 5 minutes, slice into bite-sized strips, and layer over grain bowls!"
      ],
      icon: "??"
    },
    {
      id: "recipe-saffron-rice",
      title: "Copycat Saffron Basmati Rice",
      prepTime: "20 mins",
      difficulty: "Easy",
      calories: "190 cal/serving",
      description: "Fluffy, aromatic golden basmati rice that serves as the foundation for CAVA bowls.",
      ingredients: [
        "1.5 cups long-grain white Basmati rice (rinsed)",
        "2.5 cups vegetable or chicken broth",
        "1 pinch saffron threads (steeped in 2 tbsp warm water)",
        "1/2 tsp ground turmeric (for golden color)",
        "1 tbsp olive oil or butter, sea salt"
      ],
      steps: [
        "Rinse basmati rice until water runs clear.",
        "In a saucepan, heat olive oil, toast turmeric and rinsed rice for 1 minute.",
        "Pour in broth and saffron water. Bring to a boil, then cover and reduce to low heat.",
        "Simmer 15 minutes, remove from heat, let steam 5 minutes, and fluff with a fork."
      ],
      icon: "??"
    }
  ],

  promoCodes: {
    "CAVALOVER15": { discountPercent: 15, description: "15% off your Mediterranean feast" },
    "FRESH20": { discountPercent: 20, description: "20% off orders over $25" },
    "TASTECAVA": { discountAmount: 5.00, description: "$5.00 off welcome reward" },
    "STUDENT10": { discountPercent: 10, description: "10% off Student Special (Mon-Thu)" }
  },

  locations: [
    { id: "loc-1", name: "CAVA — University Place", address: "University Place", distance: "0.8 miles", status: "Open Now", hours: "10:45 AM – 10:00 PM (7 Days)", readyIn: "15-20 min" },
    { id: "loc-2", name: "CAVA Bethesda Original", address: "7800 Wisconsin Ave, Bethesda MD", distance: "Historic Flagship", status: "Open Now", hours: "10:45 AM � 10:00 PM", readyIn: "10-15 min" },
    { id: "loc-3", name: "CAVA Midtown Plaza", address: "780 Lexington Blvd", distance: "2.1 miles", status: "Open Now", hours: "10:45 AM � 10:00 PM", readyIn: "20-25 min" }
  ]
};





